/**
 * Disposable / temporary email domain blocklist.
 *
 * Curated from disposable-email-domains, tempail, guerrillamail, and
 * other public lists. Used to reject signups from known throwaway email
 * providers at the authentication gate.
 *
 * Last updated: 2026-09-19
 */

/* eslint-disable */
const DISPOSABLE_DOMAINS = new Set([
  // Guerrilla Mail family
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.de',
  'guerrillamail.biz',
  'guerrillamail.info',
  'guerrillamailblock.com',
  'sharklasers.com',
  'guerrillamail.co',
  'guerrillamail.in',
  'guerrillamail.fr',
  'guerrillamail.se',
  'guerrillamail.ch',
  'guerrillamail.ca',
  'guerrillamail.ws',
  'grr.la',
  'guerrillas.com',
  // Mailinator family
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator.io',
  'maildrop.cc',
  'mailnesia.com',
  'mailcatch.com',
  'mailnull.com',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslurp.com',
  'mailsorter.com',
  'mailthrowaway.com',
  'mailtrash.net',
  'mailzilla.com',
  // Temp-mail family
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  'temp-mail.ru',
  'temp-mail.top',
  'tempail.com',
  'tempalias.com',
  'tempinbox.com',
  'tempinbox.co.uk',
  'templemail.com',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryemailaddress.com',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporary-mail.info',
  'temporary-mail.net',
  'temporary-mail.org',
  'temporary-mail.us',
  'temporaryemail.info',
  'temporaryemail.org',
  'tempomail.fr',
  'temporarily.de',
  // YOPmail family
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yopmail.gq',
  'yopmail.info',
  'yopmail.in',
  'yopmail.ir',
  // 10 Minute Mail family
  '10minutemail.com',
  '10minutemail.co.uk',
  '10minutemail.co.za',
  '10minutemail.de',
  '10minutemail.info',
  '10minutemail.net',
  '10minutemail.org',
  '10minutemail.us',
  '10minutemail.nl',
  '10minutemail.pl',
  '10minutemail.se',
  '10minutemail.it',
  // ThrowAway / TrashEmail
  'throwaway.email',
  'trashmail.com',
  'trashmail.net',
  'trashmail.org',
  'trashmail.me',
  'trashmail.io',
  'trashmail.info',
  'trashmail.de',
  'trashmail.at',
  'trashmail.ch',
  'trashmail.fr',
  'trashmail.be',
  'trashmail.ws',
  'trashmail.ninja',
  'trashmail.top',
  'trashemail.de',
  'trbvn.com',
  // Fake / Temp / Disposable
  'fakemailgenerator.com',
  'fakemail.xyz',
  'fakeinbox.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'disposable.cf',
  'disposable.ga',
  'disposable.ml',
  'disposable.email',
  'disposableaddress.com',
  'disposableinbox.com',
  'disposablemail.com',
  'disposable-message.com',
  'disposablepost.com',
  'disposablewebmail.com',
  'dispostable.com',
  // GetNada / AirMail
  'getnada.com',
  'getairmail.com',
  'get-mail.cf',
  'get-mail.ga',
  'get-mail.xyz',
  'get-mail.top',
  'get2mail.fr',
  'getonemail.com',
  'getonemail.net',
  'getsomebox.com',
  // MailMe / MyTemp
  'mailme24.com',
  'mailme.ir',
  'mailme.lv',
  'mailme.org',
  'mytemp.email',
  'mytempmail.com',
  'mytempemail.com',
  // MeltMail / MohMal
  'meltmail.com',
  'mohmal.com',
  'mohmal.im',
  'mohmal.in',
  'mohmal.info',
  // MintEmail / Mailforspam
  'mintemail.com',
  'mailforspam.com',
  'mail-for-spa.com',
  'mailfor.us',
  // Spamgourmet / SpamHopper
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamhopper.com',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  // Tmail / TempInbox
  'tmail.com',
  'tmail.io',
  'tmail.org',
  'tmail.ws',
  'tmail.top',
  'tmpmail.com',
  'tmpmail.net',
  'tmpmail.org',
  'tmpmail2.com',
  'tmpmailer.com',
  // AnonMail
  'anonbox.net',
  'anonymbox.com',
  'anonymize.com',
  'anonymize.org',
  'anonmails.de',
  'anonmailer.net',
  'anonimbox.com',
  'anonymous-email.net',
  // BugMeNot / Crazymailing
  'bugmenot.com',
  'crazymailing.com',
  'crazymailing.net',
  // EmailOnDeck
  'emailondeck.com',
  'emailigo.de',
  'emailinfive.com',
  'emaillime.com',
  'emailmiser.com',
  'emailproxsy.com',
  'emails.ga',
  'emailsensei.com',
  'emailtemporario.com.br',
  'emailtemporanea.com.br',
  'emailtemporanea.de',
  'emailtemporanea.net',
  'emailtemporanea.ro',
  'emailthe.net',
  'emailtmp.com',
  'emailto.de',
  'emailwarden.com',
  'emailxfer.com',
  // Einrot / FakeEmail
  'einrot.com',
  'einrot.de',
  'faked-email.com',
  'fakemail.fr',
  'fivemail.de',
  'fizmail.com',
  // FriendMail
  'friendmail.com',
  'friendmail.de',
  'friendmail.eu',
  'friendmail.me',
  'friendmail.net',
  'friendmail.org',
  'friendmail.top',
  'friendmail.us',
  // GhostText / GishPuppy
  'ghosttexter.de',
  'ghosttexter.info',
  'ghosttexter.net',
  'gishpuppy.com',
  // GoMail / GotMail
  'goemailgo.com',
  'gotmail.com',
  'gotmail.net',
  'gotmail.org',
  'gotmail.top',
  // H8Mail / Harakiri
  'h8mail.com',
  'harakirimail.com',
  'hartbot.de',
  // HideBox / HideEmail
  'hidebox.org',
  'hidebusiness.biz',
  'hidemail.fr',
  'hidemail.net',
  'hidemail.pro',
  'hulapla.de',
  // IMBOX
  'imbox.org',
  // InboxClean
  'inboxclean.com',
  'inboxclean.org',
  'inboxme.me',
  'inboxproxy.com',
  // IncognitoMail
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'incognitomail.pro',
  'incognitomail.ws',
  // Insorg
  'insorg-mail.info',
  // LixMail
  'lixmail.com',
  'lixmail.net',
  // LortEmail
  'lortemail.dk',
  // Mail-Bak
  'mail-bak.com',
  // Mail21
  'mail21.cc',
  'mail21.net',
  // Mail2Tor
  'mail2tor.com',
  // Mail333
  'mail333.com',
  // MailBucket
  'mailbucket.org',
  // MailCat
  'mailcat.biz',
  // MailChip
  'mailchip.net',
  // MailDrain
  'maildrain.info',
  // MailForspam
  'mailforspam.com',
  // MailFree
  'mailfree.ga',
  'mailfree.gq',
  'mailfree.ml',
  'mailfree.onl',
  // MailGive
  'mailgive.rocks',
  // MailHazard
  'mailhazard.com',
  'mailhazard.us',
  // MailHelp
  'mailhelp.org',
  // MailHz
  'mailhz.me',
  // MailInAtor
  'mailinator.com',
  'mailinator2.com',
  // MailIsPending
  'mailispending.com',
  // MailKo
  'mailko.com',
  'mailko.net',
  // MailMate
  'mailmate.com',
  // MailMe
  'mailme.ir',
  'mailme.lv',
  'mailme.org',
  // MailMoat
  'mailmoat.com',
  // MailNow
  'mailnow2.com',
  'mailnow2.net',
  // MailPick
  'mailpick.biz',
  // MailPro
  'mailproxsy.com',
  // MailQuack
  'mailquack.com',
  // MailRock
  'mailrock.biz',
  // MailScrap
  'mailscrap.com',
  // MailShell
  'mailshell.com',
  // MailSiphon
  'mailsiphon.com',
  // MailSlip
  'mailslip.com',
  // MailSlurp
  'mailslurp.com',
  // MailSorter
  'mailsorter.com',
  // MailTech
  'mailtechx.com',
  // MailTest
  'mailtest.info',
  // MailThis
  'mailthis.us',
  // MailThrowaway
  'mailthrowaway.com',
  // MailTo
  'mailtothis.com',
  // MailTrash
  'mailtrash.net',
  // MailTV
  'mailtv.net',
  'mailtv.tv',
  // MailZilla
  'mailzilla.com',
  'mailzilla.net',
  'mailzilla.org',
  // MailZur
  'mailzur.com',
  // MeltMail
  'meltmail.com',
  // MessageLock
  'messagelock.me',
  // MintMail
  'mintemail.com',
  // Moakt
  'moakt.com',
  'moakt.co',
  'moakt.cc',
  'moakt.net',
  // MobiQuiz
  'mobiquo.com',
  // MollieMail
  'molliemail.com',
  // MondoMail
  'mondnomaster.com',
  // MoongMail
  'moong-mail.com',
  // MOPMail
  'mopmail.com',
  // My10MinMail
  'my10minutemail.com',
  // MyAlias
  'myalias.pw',
  // MyCleanInbox
  'mycleaninbox.net',
  // MyEmailFor
  'myemailboxy.com',
  // MyTemp
  'mytemp.email',
  'mytemp.emailsneak.net',
  'mytempmail.com',
  'mytempemail.com',
  // Nada
  'nada.email',
  'nada.king',
  // Negated
  'negated.com',
  // Net3mail
  'net3mail.com',
  // NeutralTone
  'neutrality.email',
  // No-Spam
  'no-spam.ws',
  'no-spam.de',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'nospamthanks.info',
  // Nothing
  'nothingtoseehere.ca',
  // Nurfuerspam
  'nurfuerspam.de',
  // OddPost
  'oddpost.com',
  // OneTimeEmail
  'onetimemail.com',
  'onetimemail.org',
  'onetimedomain.com',
  // OnWayMail
  'onewaymail.com',
  // Oo.la.la
  'oo.la.la',
  // O-mail
  'o-mail.us',
  // OppB
  'oppb.net',
  // OrgFree
  'orgmailfree.com',
  // OwlPic
  'owlpic.com',
  // PCMail
  'pcmailING.com',
  // PimpedMail
  'pimped.email',
  // Pkaytea
  'pkaytea.com',
  // PookMail
  'pookmail.com',
  // Privacy.net
  'privacy.net',
  // PrivacyMail
  'privacymail.info',
  // Privatdemail
  'privatdemail.net',
  // ProxyMail
  'proxymail.eu',
  // Prtnx
  'prtnx.com',
  // PunkAss
  'punkass.com',
  // PutThisInYourMailbox
  'putthisinyouremail.com',
  // QuickMailing
  'quickmail.nl',
  // RCPT
  'rcpt.at',
  'rcpt.me',
  // ReallyMailable
  'reallymailable.com',
  // Recode
  'recode.me',
  // Rentry
  'rentry.co',
  // S0ny
  's0ny.net',
  // SafeMail
  'safe-mail.net',
  'safemail.de',
  'safersignup.de',
  'safetymail.info',
  // Saltag
  'saltag.com',
  // Sandelf
  'sandelf.de',
  // Saynotospams
  'saynotospams.com',
  // Scatmail
  'scatmail.com',
  // Schafmail
  'schafmail.de',
  // SecureMail
  'secure-mail.biz',
  'secure-mail.cc',
  // SelfDestruct
  'selfdestructingmail.com',
  'selfdestructingmail.org',
  // SendeMail
  'sendmea.link',
  // SendSpamHere
  'sendspamhere.com',
  // ShakeBaby
  'shakebaby.de',
  // ShiftMyMail
  'shiftmail.com',
  // ShowMy
  'showmy.info',
  // SibMail
  'sibmail.com',
  // Sinnlos
  'sinnlos-mail.de',
  // SkeefMail
  'skeefmail.com',
  // Slask
  'slaskpost.se',
  // Sluttyspam
  'sluttyspam.com',
  // SmashMail
  'smashmail.de',
  // SmellFungus
  'smellfungus.com',
  // SmetteMail
  'smethi.tk',
  // SMSMail
  'smsmail.de',
  // Snakemail
  'snakemail.com',
  // SnaPub
  'snapdo.com',
  // SneakEmail
  'sneakemail.com',
  'sneakymail.de',
  // Sob
  'sob.su',
  // SogetThis
  'sogetthis.com',
  'sogetthis.net',
  // Soodonims
  'soodonims.com',
  // Spam
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambog.uk',
  'spambog.us',
  'spambox.info',
  'spambox.irishspringrealty.com',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfighter.cf',
  'spamfighter.ga',
  'spamfighter.gq',
  'spamfighter.ml',
  'spamfighter.tk',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgiant.com',
  'spamgiant.net',
  'spamgiant.org',
  'spamgoes.in',
  'spamgrid.com',
  'spamhere.com',
  'spamhere.info',
  'spamhere.us',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spaminc.jp',
  'spamity.com',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spamlotion.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtrap.ro',
  // Speed.ig
  'speed.ig42.com',
  // Squizzy
  'squizzy.de',
  // Sry
  'sry.com',
  // Start
  'start-phone.com',
  // Supermailer
  'supermailer.jp',
  // Superrito
  'superrito.com',
  // Superstachel
  'superstachel.de',
  // SWBEL
  'swbel.com',
  // SWebby
  'swebby.com',
  // TAFMAIL
  'tafmail.com',
  // Talkinator
  'talkinator.com',
  // TapChg
  'tapchicuoihoi.com',
  // Teewars
  'teewars.org',
  // Telegraph
  'teleworm.com',
  'teleworm.us',
  // TempInbox
  'temp-inbox.com',
  'temp-inbox.info',
  // TempMail
  'tempmail.eu',
  'tempmail.it',
  'tempmail.it',
  'tempmail.plus',
  // TempMailo
  'tempmailo.com',
  // TempMailZone
  'tempmailzone.com',
  // TempMailed
  'tempmailed.com',
  // TempPost
  'temppost.com',
  // TempSmtp
  'tempsmtp.com',
  // TempTheMail
  'tempthemail.com',
  // TenMail
  'tenemail.de',
  // TeStam
  'test.com',
  'test.de',
  // ThankYou2010
  'thankyou2010.com',
  // TheCloudIndex
  'thecloudindex.com',
  // TheLastSupper
  'thelastsupper.com',
  // ThunderAtta
  'thunder-atlas.com',
  // Tittbit
  'tittbit.in',
  // Tizi
  'tizi.com',
  'tizi.in',
  'tizi.la',
  'tizi.me',
  // Tmailinator
  'tmailinator.com',
  // TN
  'tn.to',
  // TOIEC
  'toiea.com',
  // ToieaMail
  'toieamail.com',
  // TopMail
  'topmail.com',
  'topmail.kz',
  // TorchMail
  'torchmail.com',
  // TPJail
  'tpjail.com',
  // Trash-It
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash-mail.me',
  'trash-mail.net',
  'trash-mail.org',
  'trash-me.com',
  'trasha.net',
  'trashbay.com',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashmailer.de',
  'trashymail.com',
  'trashymail.net',
  // TrickMail
  'trickmail.net',
  // Triple
  'tripledev.iredmail.com',
  // TSPM
  'tspmail.com',
  // Turual
  'turual.com',
  // TwinEmail
  'twinmail.de',
  // Tyldd
  'tyldd.com',
  // TyMail
  'tyldd.com',
  // Uggs
  'uggsrock.com',
  // Uin8
  'uin8.com',
  // Uk.to
  'uk.to',
  // Ultrasw
  'ultrasw.com',
  // UnMail
  'unmail.ru',
  // Upliftnow
  'upliftnow.com',
  'uplipht.com',
  // VenomPen
  'venompen.com',
  // VidaL
  'vidchart.com',
  'viditag.com',
  'viewcastmedia.com',
  // VOMail
  'vonmail.net',
  'vonmail.org',
  // Vorsorge
  'vorsorge-per-mail.de',
  // WarpMail
  'warpmail.net',
  // WebMails
  'webmails.de',
  // Weg-Werf
  'weg-werf-email.de',
  'weg-werf-emails.de',
  'weg-werf-mail.de',
  'wegwerfadresse.com',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfemail.info',
  'wegwerfemail.net',
  'wegwerfemail.org',
  'wegwerf-emails.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wegwerfmail24.de',
  'wegwerfmailadresse.de',
  'wegwerfemails.de',
  'wegwerfemailse.de',
  'wegwerfmails.de',
  'wegwerfpost.net',
  'wegwerfpost.org',
  'wegwerppost.de',
  // Wh4f
  'wh4f.org',
  // WhatOnMyMind
  'whatsonmymind.com',
  // WhereGit
  'wheregit.com',
  // Whyspam
  'whyspam.me',
  // Wikidocuslice
  'wikidocuslice.com',
  // WillHackFor
  'willhackforfood.biz',
  // Willie
  'williamshome.net',
  // WinIT
  'winqa.com',
  // WolfSm
  'wolfsmail.com',
  // WileE
  'wilemail.com',
  // WowDot
  'wowdot.com',
  // WP
  'wp.pl',
  // Xagloo
  'xagloo.com',
  'xagloo.net',
  'xagloo.org',
  // Xemaps
  'xemaps.com',
  // Xents
  'xents.com',
  // Xjoi
  'xjoi.com',
  'xjoi.net',
  // XMailo
  'xmailo.com',
  'xmailo.net',
  // XMen
  'xmen119.com',
  // XOXO
  'xoxomo.com',
  'xoxoxo.ee',
  // Xrea
  'xrea.com',
  // Yapped
  'yapped.net',
  // YepIt
  'yeptp.com',
  // Yeshmail
  'yeshmail.com',
  // Yogamaven
  'yogamaven.com',
  // Yomail
  'yomail.info',
  // Yopmail
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yopmail.gq',
  // YouSpam
  'youspam.de',
  // Yuurok
  'yuurok.com',
  // ZipZoom
  'zipzoom.us',
  // ZehnMinutenMail
  'zehnminutenmail.de',
  // Zippymail
  'zippymail.info',
  // Zohomail (free but commonly abused)
  // Note: not blocking zoho.com as it has legit users

  // Additional high-volume disposable services
  'aaatempmail.com',
  'abyssmail.com',
  'ajaxapp.net',
  'alivance.com',
  'amail.com',
  'amilegit.com',
  'amiri.net',
  'antireg.ru',
  'artman-conception.com',
  'azmeil.tk',
  'baxomale.ht.cx',
  'bearsarefuzzy.com',
  'beefmilk.com',
  'bigstring.com',
  'binkmail.com',
  'bio-muesli.net',
  'bladesmail.net',
  'bloatbox.com',
  'bobmail.info',
  'bodhi.lawlita.com',
  'bofthew.com',
  'bootybay.de',
  'boun.cr',
  'bouncr.com',
  'breakthru.com',
  'brefmail.com',
  'brennendesreich.de',
  'broadbandninja.com',
  'bsnow.net',
  'bspamfree.org',
  'buffemail.com',
  'bugmenot.com',
  'bumpymail.com',
  'bundes-ede.de',
  'buxap.com',
  'californiamail.com',
  'cash4mail.com',
  'cashforspam.com',
  'catemail.com',
  'causachun.com',
  'cbair.com',
  'chammy.info',
  'cheatmail.de',
  'chogmail.com',
  'choicemail1.com',
  'clipmail.eu',
  'clixser.com',
  'cmail.net',
  'cmail.org',
  'coldemail.info',
  'cool.fr.nf',
  'courriel.fr.nf',
  'courrieltemporaire.com',
  'crapmail.org',
  'crazymailing.com',
  'cubiclink.com',
  'curryworld.de',
  'cust.in',
  'cuvox.de',
  'd3p.dk',
  'dacoolest.com',
  'dandikmail.com',
  'dayrep.com',
  'dcemail.com',
  'deadaddress.com',
  'deadspam.com',
  'delikkt.de',
  'despammed.com',
  'devnullmail.com',
  'dfgh.net',
  'digitalsanctuary.com',
  'dingbone.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'disposable.cf',
  'disposable.ga',
  'disposable.ml',
  'disposable.email',
  'disposableaddress.com',
  'disposableemailaddresses.emailmiser.com',
  'disposableinbox.com',
  'disposablemail.com',
  'disposable-message.com',
  'disposablepost.com',
  'disposablewebmail.com',
  'dispostable.com',
  'dodgeit.com',
  'dodgit.com',
  'dodgit.org',
  'dontreg.com',
  'dontsendmespam.de',
  'drdrb.com',
  'drdrb.net',
  'droplar.com',
  'dropmail.me',
  'duam.net',
  'dudmail.com',
  'dump-email.info',
  'dumpandjunk.com',
  'dumpyemail.com',
  'e-mail.com',
  'e-mail.org',
  'e4ward.com',
  'easytrashmail.com',
  'ee1.pl',
  'ee2.pl',
  'eelmail.com',
  'einmalmail.de',
  'einrot.com',
  'einrot.de',
  'eintagsmail.de',
  'email-fake.cf',
  'email-fake.com',
  'email-fake.ga',
  'email-fake.gq',
  'email-fake.ml',
  'email-fake.tk',
  'email60.com',
  'emailage.cf',
  'emailage.ga',
  'emailage.gq',
  'emailage.ml',
  'emailage.tk',
  'emaildienst.de',
  'emailigo.de',
  'emailinfive.com',
  'emaillime.com',
  'emailmiser.com',
  'emailproxsy.com',
  'emails.ga',
  'emailsensei.com',
  'emailtemporario.com.br',
  'emailtemporario.ro',
  'emailtemporanea.com.br',
  'emailtemporanea.de',
  'emailtemporanea.net',
  'emailtemporanea.ro',
  'emailthe.net',
  'emailtmp.com',
  'emailto.de',
  'emailwarden.com',
  'emailx.at.hm',
  'emailxfer.com',
  'emz.net',
  'enterto.com',
  'ephemail.net',
  'etranquil.com',
  'etranquil.net',
  'etranquil.org',
  'evopo.com',
  'explodemail.com',
  'express.net.ua',
  'eyepaste.com',
  'fakeinbox.com',
  'fakeinformation.com',
  'fakemail.fr',
  'fakemailz.com',
  'fammix.com',
  'fansworldwide.de',
  'fantasymail.de',
  'fastacura.com',
  'fastchevy.com',
  'fastchrysler.com',
  'fastkawasaki.com',
  'fastmazda.com',
  'fastmitsubishi.com',
  'fastnissan.com',
  'fastsubaru.com',
  'fastsuzuki.com',
  'fasttoyota.com',
  'fastyamaha.com',
  'fightallspam.com',
  'filzmail.com',
  'find-spam.com',
  'fizmail.com',
  'fizmail.eu',
  'flashbox.5july.org',
  'fleetstreetpost.com',
  'flemail.de',
  'flyspam.com',
  'footard.com',
  'forgetmail.com',
  'fr33mail.info',
  'frapmail.com',
  'freemails.cf',
  'freemails.ga',
  'freemails.ml',
  'free-01.web-02.europa-online.net',
  'freundin.ru',
  'friendlymail.co.uk',
  'front14.org',
  'fuckingduh.com',
  'fudgerub.com',
  'fux0ringduh.com',
  'fyii.de',
  'garliclife.com',
  'gehensiuli.com',
  'get-mail.cf',
  'get-mail.ga',
  'get-mail.gq',
  'get-mail.ml',
  'get-mail.tk',
  'get-mail.top',
  'get2mail.fr',
  'getairmail.cf',
  'getairmail.com',
  'getairmail.ga',
  'getairmail.gq',
  'getairmail.ml',
  'getairmail.tk',
  'getmails.eu',
  'getonemail.com',
  'getonemail.net',
  'ghosttexter.de',
  'ghosttexter.info',
  'ghosttexter.net',
  'girlsundertheinfluence.com',
  'gishpuppy.com',
  'goemailgo.com',
  'gorillaswithdirtyarmpits.com',
  'gotmail.com',
  'gotmail.net',
  'gotmail.org',
  'gowikibooks.com',
  'gowikicars.com',
  'gowikigames.com',
  'gowikimusic.com',
  'gowikinetwork.com',
  'gowikitravel.com',
  'grandmamail.com',
  'great-host.in',
  'greensloth.com',
  'greermail.com',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'guerrillamail.info',
  'guerrillamail.se',
  'grr.la',
  'gsrv.co.uk',
  'guerrillamail.ch',
  'guerrillamail.com.br',
  'guerrillamail.developers.com',
  'guerrillamail.de',
  'gustr.com',
  'h8mail.com',
  'hacccc.com',
  'haltospam.com',
  'harakirimail.com',
  'hartbot.de',
  'hat-givers.com',
  'hatespam.eu',
  'herp.in',
  'hidemail.fr',
  'hidemail.net',
  'hidemail.pro',
  'hidzz.com',
  'hmamail.com',
  'hopemail.biz',
  'hot-mail.cf',
  'hot-mail.ga',
  'hot-mail.gq',
  'hot-mail.ml',
  'hot-mail.tk',
  'hotpop.com',
  'hulapla.de',
  'hushmail.com',
  'ichimail.com',
  'imails.info',
  'inbax.tk',
  'inbox.si',
  'inbox100.com',
  'inbox25.com',
  'inboxclean.com',
  'inboxclean.org',
  'inboxproxy.com',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'infocom.zp.ua',
  'inoutmail.de',
  'inoutmail.info',
  'inoutmail.net',
  'insorg-mail.info',
  'ipoo.org',
  'irish2me.com',
  'iwi.net',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'jnxjn.com',
  'jourrapide.com',
  'jsrsolutions.com',
  'kasmail.com',
  'kaspop.com',
  'keepmymail.com',
  'killmail.com',
  'killmail.net',
  'kingsq.ga',
  'kir.ch.tc',
  'klassmaster.com',
  'klassmaster.net',
  'klzlk.com',
  'kook.ml',
  'kurzepost.de',
  'lawlita.com',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lol.ovpn.to',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lovemeleaveme.com',
  'lr78.com',
  'lroid.com',
  'lukop.dk',
  'm21.cc',
  'maboard.com',
  'mail-temporaire.fr',
  'mail.by',
  'mail.mezimages.net',
  'mail.zp.ua',
  'mail114.net',
  'mail1a.de',
  'mail1x.de',
  'mail21.cc',
  'mail21.net',
  'mail2rss.org',
  'mail333.com',
  'mail4trash.com',
  'mailbidon.com',
  'mailblocks.com',
  'mailblog.biz',
  'mailbucket.org',
  'mailcat.biz',
  'mailcatch.com',
  'maildrop.cc',
  'maildu.de',
  'maildx.com',
  'maileater.com',
  'mailed.ro',
  'maileimer.de',
  'mailexpire.com',
  'mailfa.tk',
  'mailforspam.com',
  'mailfree.ga',
  'mailfree.gq',
  'mailfree.ml',
  'mailfree.onl',
  'mailfs.com',
  'mailguard.me',
  'mailhazard.us',
  'mailhz.me',
  'mailimate.com',
  'mailin8r.com',
  'mailinater.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator.us',
  'mailinator2.com',
  'mailincubator.com',
  'mailismag.com',
  'mailmate.com',
  'mailme.ir',
  'mailme.lv',
  'mailme.org',
  'mailme24.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnator.com',
  'mailnesia.com',
  'mailnull.com',
  'mailorg.org',
  'mailpick.biz',
  'mailproxsy.com',
  'mailquack.com',
  'mailrock.biz',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslip.com',
  'mailslurp.com',
  'mailslurp.me',
  'mailsorter.com',
  'mailspam.biz',
  'mailspam.info',
  'mailspam.us',
  'mailsurf.com',
  'mailtechx.com',
  'mailtemp.info',
  'mailtemporaire.fr',
  'mailtest.info',
  'mailthis.us',
  'mailthrowaway.com',
  'mailto.de',
  'mailtothis.com',
  'mailtrash.net',
  'mailtv.net',
  'mailtv.tv',
  'mailuse.com',
  'mailville.com',
  'mailzilla.com',
  'mailzilla.net',
  'mailzilla.org',
  'makemetheking.com',
  'manifestgenerator.com',
  'manybrain.com',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'mezimages.net',
  'mfsa.ru',
  'mierdamail.com',
  'migmail.pl',
  'migumail.com',
  'mindless.com',
  'ministry-of-silly-walks.de',
  'mintemail.com',
  'misterpinball.de',
  'mmmmail.com',
  'moakt.com',
  'mobi.web.id',
  'mohmal.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'monumentmail.com',
  'msa.minsmail.com',
  'mx0.wwwnew.eu',
  'my10minutemail.com',
  'myalias.pw',
  'mycleaninbox.net',
  'myemailboxy.com',
  'mymail-in.net',
  'mymailoasis.com',
  'mymailuk.com',
  'myninton.com',
  'mysamp.de',
  'myspaceinc.com',
  'myspaceinc.net',
  'myspaceinc.org',
  'myspacepimpedup.com',
  'mytemp.email',
  'mytempmail.com',
  'mytempemail.com',
  'mytempemail.org',
  'mytempinbox.com',
  'mytempmail.com',
  'mytempemail.com',
  'mytempemail.org',
  'mytempinbox.com',
  'mytempmail.org',
  'nabala.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'nervtansen.de',
  'netmails.com',
  'netmails.net',
  'neverbox.com',
  'nice-4u.com',
  'nincsmail.hu',
  'nnh.com',
  'no-spam.for-our.info',
  'no-spam.ws',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.xl.cx',
  'nomail2me.com',
  'nomorespamemails.com',
  'nonspam.eu',
  'nonspammer.de',
  'noref.in',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'nospamthanks.info',
  'nothingtoseehere.ca',
  'novamail.net',
  'nui.nu',
  'nwldx.com',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'oopi.org',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pimped.email',
  'pjjkp.com',
  'plexolan.de',
  'poczta.onet.pl',
  'politikerclub.de',
  'poofy.org',
  'pookmail.com',
  'privacy.net',
  'privacy4mail.com',
  'privatdemail.net',
  'proxymail.eu',
  'prtnx.com',
  'punkass.com',
  'putthisinyouremail.com',
  'qqmail.cf',
  'qqmail.ga',
  'quickinbox.com',
  'quickmail.nl',
  'rcpt.at',
  'rcpt.me',
  'reallymailable.com',
  'recode.me',
  'recursor.net',
  'regbypass.com',
  'regbypass.comsafe.net',
  'reliable-mail.com',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  'rtrtr.com',
  'rzelder.email',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'scatmail.com',
  'schafmail.de',
  'schrott-email.de',
  'secretemail.de',
  'secure-mail.biz',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'sftu.net',
  'shitmail.me',
  'shitmail.org',
  'shitware.nl',
  'shmeriously.com',
  'shortmail.net',
  'sibmail.com',
  'sinnlos-mail.de',
  'skeefmail.com',
  'slaskpost.se',
  'slipry.net',
  'slopsbox.com',
  'slowslow.de',
  'slugmail.com',
  'slutty.horse',
  'smashmail.de',
  'smellfungus.com',
  'smntp.com',
  'snakemail.com',
  'sneakemail.com',
  'sneakymail.de',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'softpls.asia',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambog.uk',
  'spambog.us',
  'spambox.info',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfighter.cf',
  'spamfighter.ga',
  'spamfighter.gq',
  'spamfighter.ml',
  'spamfighter.tk',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgiant.com',
  'spamgiant.net',
  'spamgiant.org',
  'spamgoes.in',
  'spamgrid.com',
  'spamhere.com',
  'spamhere.info',
  'spamhere.us',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spaminc.jp',
  'spamity.com',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spamlotion.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtrap.ro',
  'speed.ig42.com',
  'squizzy.de',
  'sry.com',
  'sibmail.com',
  'sinnlos-mail.de',
  'skeefmail.com',
  'slaskpost.se',
  'slutty.horse',
  'sneakemail.com',
  'sneakymail.de',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambog.uk',
  'spambog.us',
  'spambox.info',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgiant.com',
  'spamgiant.net',
  'spamgiant.org',
  'spamgoes.in',
  'spamgrid.com',
  'spamhere.com',
  'spamhere.info',
  'spamhere.us',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spaminc.jp',
  'spamity.com',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spamlotion.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtrap.ro',
  'speed.ig42.com',
  'squizzy.de',
  'sry.com',
  'superrito.com',
  'superstachel.de',
  'svk.jp',
  'sweetxxx.de',
  'sweetheartmail.com',
  'tafmail.com',
  'talkinator.com',
  'tapchicuoihoi.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp-inbox.com',
  'temp-mail.org',
  'temp-mail.ru',
  'temp-mail.top',
  'temp-mail.io',
  'temp.headweb.com',
  'temp1.m0st.com',
  'temp2.m0st.com',
  'temp4you.com',
  'tempail.com',
  'tempalias.com',
  'tempano.com',
  'tempate.com',
  'tempemail.biz',
  'tempemail.co.za',
  'tempemail.com',
  'tempemail.net',
  'tempemail.org',
  'tempemail.us',
  'tempemailbox.com',
  'tempemaildomain.com',
  'tempemailfree.com',
  'tempemailnow.com',
  'tempemailonline.com',
  'tempemailpro.com',
  'tempemailx.com',
  'tempinbox.com',
  'tempinbox.co.uk',
  'tempmail.eu',
  'tempmail.it',
  'tempmail.it',
  'tempmail.plus',
  'tempmail2.de',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempmailo.com',
  'tempmailed.com',
  'tempmailonline.com',
  'tempmailpro.com',
  'tempmailusa.com',
  'tempmailzone.com',
  'tempo-mail.org',
  'tempomail.fr',
  'temporarily.de',
  'temporaryemailaddress.com',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryemaildomain.com',
  'temporaryemailfree.com',
  'temporaryemailnow.com',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporaryinbox.net',
  'temporaryinbox.org',
  'temporary-mail.info',
  'temporary-mail.net',
  'temporary-mail.org',
  'temporary-mail.us',
  'temporarypost.net',
  'temptheemail.com',
  'tempthemail.com',
  'tenemail.de',
  'tenmail.tech',
  'thankyou2010.com',
  'thecloudindex.com',
  'thelastsupper.com',
  'thrma.com',
  'throam.com',
  'thrott.com',
  'tittbit.in',
  'tizi.com',
  'tizi.in',
  'tizi.la',
  'tizi.me',
  'tmailinator.com',
  'tmails.org',
  'toiea.com',
  'toieamail.com',
  'toomail.biz',
  'topmail.kz',
  'topspammers.com',
  'trailermus.com',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash-mail.me',
  'trash-mail.net',
  'trash-mail.org',
  'trash-me.com',
  'trash.to',
  'trash2009.com',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashmailer.de',
  'trashmailo.com',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'trbvn.com',
  'trbvp.com',
  'trbvt.com',
  'trickmail.net',
  'trillionparty.com',
  'trollbna.com',
  'tropicalbreeze.info',
  'trungnam.ml',
  'ttszuo.shop',
  'turboprinz.de',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'typ.email',
  'typo.ing',
  'u2nh.com',
  'uggsrock.com',
  'uk.to',
  'umail.net',
  'umail.us',
  'upliftnow.com',
  'uplipht.com',
  'venompen.com',
  'veryrealliemail.com',
  'vidchart.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'vomail.de',
  'vpn01.de',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'wasteland.rfc822.org',
  'webemail.me',
  'weg-werf-email.de',
  'weg-werf-emails.de',
  'weg-werf-mail.de',
  'wegwerfadresse.de',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfemail.info',
  'wegwerfemail.net',
  'wegwerfemail.org',
  'wegwerfemails.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wegwerfmail24.de',
  'wegwerfmailadresse.de',
  'wegwerfpost.de',
  'wegwerfpost.net',
  'wegwerfpost.org',
  'wenku.com',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whyspam.me',
  'wickmail.net',
  'wilemail.com',
  'willhackforfood.biz',
  'williamshome.net',
  'winemaven.info',
  'wirsindkeinspam.de',
  'wissenisttoll.de',
  'wizwiz.co.uk',
  'wmail.eu',
  'wontok.com',
  'wpd.sh',
  'wuzup.net',
  'wuzupmail.net',
  'xagloo.com',
  'xagloo.net',
  'xagloo.org',
  'xemaps.com',
  'xents.com',
  'xjoi.com',
  'xjoi.net',
  'xmailo.com',
  'xmailo.net',
  'xmen119.com',
  'xoxomo.com',
  'xoxoxo.ee',
  'xrea.com',
  'xtp.de',
  'xtrafick.com',
  'yapped.net',
  'yeptp.com',
  'yeshmail.com',
  'yogamaven.com',
  'yomail.info',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yopmail.gq',
  'yopmail.info',
  'yopmail.in',
  'yopmail.ir',
  'you-spam.de',
  'you-spam.net',
  'you-spam.org',
  'youremail.info',
  'yourtube.mooo.com',
  'yuurok.com',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoemail.org',
]);
/* eslint-enable */

/**
 * Check if an email address belongs to a known disposable / temp mail domain.
 *
 * Performs case-insensitive matching against the domain part only (after @).
 * Also catches common obfuscations like subdomains (foo@bar.mailinator.com).
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return false;

  // Direct match
  if (DISPOSABLE_DOMAINS.has(domain)) return true;

  // Check parent domains (e.g. foo@sub.mailinator.com → mailinator.com)
  const parts = domain.split('.');
  for (let i = 1; i < parts.length - 1; i++) {
    const parent = parts.slice(i).join('.');
    if (DISPOSABLE_DOMAINS.has(parent)) return true;
  }

  return false;
}

/**
 * Get the count of known disposable domains (for logging / diagnostics).
 */
export function getDisposableDomainCount(): number {
  return DISPOSABLE_DOMAINS.size;
}
